### ISSUE TITLE
Unmound/mount usb drive?

### ISSUE THREAD

**Issue by rocknard** [aldostools/IRISMAN#10]
Hello, Aldos. I don't know if there is a option to "unmount" the usb harddrive connected from the ps3 or not (don't remember if managunz have it). The problem is sometimes the usb harddrive is "locked" and don't sleep automatically, so i can't disconnect it without problems.

Any ideas?

Thanks (you can close the "issue" if you want).

**Comment by aldostools** [comment]
The default unmount option /mount.ps3/unmount or SELECT+CIRCLE only unmounts the last mounted game.

There is a web command /mount.ps3/unmount<dev_path> that allows to unmount devices, but to be honest I never have used it to unmount USB devices. I'm not sure if it would help.

You could create a custom combo or add it to webMAN_**.xml if you need to use it.

To prevent issues like cross linked files or corrupted file system, my suggestion is that remove the USB devices when the consoles is turned off.

**Comment by rocknard** [comment]
Ok. Thank you. I will try to see.

Thank you for your hard work, Aldos.

**Comment by rocknard** [comment]
Ok. Thank you. I will try to see.

Thank you for your hard work, Aldos.
