### ISSUE TITLE
exfat and ntfs hard drive not showing up 10tb external with on CFW Evilnat 4.90 Cobra 8.4 [CEX] and hen

### ISSUE THREAD

**Issue by syfer1987** [aldostools/IRISMAN#101]
Hi I have been puling out my hair for last 2 weeks. I have 2 ps3 one hen and CFW Evilnat 4.90 Cobra 8.4 [CEX]. Now both ps3 dont see my ntfs hard drive. I then tired  exfat and it was the same. I then tired web man mod but 0 luck. I then tried IRISMAN and its the same. I need some help. I have also tried PS3ISO and GAMEZ folder naming still 0.

**Comment by aldostools** [comment]
You probably need to try with a different USB storage device. Maybe a new pendrive.

The partition must be the first one and formatted using MBR. If the disk is over 2TB you may need to create multiple partitions or use special tools to change the sector size (which cannot be changed by regular methods). Some users have reported success changing the cluster size to 16KB, 32KB or 64KB. Even in some have reported success using clusters of 4KB.

**Comment by aldostools** [comment]
I recommend that open a thread in PSX-PLACE or Reddit asking for additional support.

**Comment by syfer1987** [comment]
Can the PS3 see more than one partition on 10 hard drives? Say if I format this with 2tb then that 5 partition on the PS3. If I do this way what folder name would I use?

**Comment by aldostools** [comment]
I personally haven't tried more than one partition.

If I recall correctly, some users have reported success using first partition formatted as NTFS and other in FAT32.

I recommend that open a thread in PSX-PLACE or Reddit asking for additional support. There you will find experts that have tried different scenarios.

This case is a configuration issue, not specific to IRISMAN. Therefore I'm closing the issue.
