### ISSUE TITLE
File Manager Freezes

### ISSUE THREAD

**Issue by refriedfood** [aldostools/IRISMAN#16]
This happens frequently, and sometimes, even after a hard reboot, will cease to even work anymore or show the panel. Might want to look into that.

**Comment by refriedfood** [comment]
IRISMAN_4.86.3

**Comment by refriedfood** [comment]
IRISMAN_4.86.3

**Comment by ozapft** [comment]
This can happen when a NTFS Drive was mounted. The File Manager writes two files to the config (path1.bin and path2.bin) to save the old used paths. When you disconnect this drive from your ps3 and restart Irisman, File Manger tries to open this old nonexistent path. You will get a freeze.
With Fat32 drives this problem does not exist. 
To prevent this, unmount the NTFS Drive in File Manger (press select+square) then exit File Manger.

**Comment by refriedfood** [comment]
I went to an older version of IRISMAN and is doesn't happen. If that is it, maybe it should be fixed.
