### ISSUE TITLE
Irisman freeze 

### ISSUE THREAD

**Issue by ozapft** [aldostools/IRISMAN#17]
Hello Aldo, 

I‘m on HEN 3.01 HFW 4.86 with a fresh install of Irisman 4.86.3
When i press the Buttons select+triangle together in the gui while a game is selected Irisman freezes. 

Thank you

**Comment by aldostools** [comment]
Try disconnecting all USB devices, then use START to select the File Manager from the menu.

Also test if previous builds don't have the error.

**Comment by ozapft** [comment]
The freeze is not during pressing select+start. I have no problem with this hotkey to open File Manager.
It happens with the hotkey Select + Triangle in the gui. Other hotkeys like Select+Square (change cover) or select+circle (restart ps3) works fine. Only select+triangle will freeze Irisman. 

EDIT: This happens only in Grid Mode with a Grid >6
pressing select+triangle is the same as pressing only triangle for the options menu but with pic1 of the game as background.
