### ISSUE TITLE
IRISMAN_4.87.pkg compiled with old language.ini

### ISSUE THREAD

**Issue by ozapft** [aldostools/IRISMAN#23]
Hello Aldo,

I’ve tested the new version 4.87. 
I want to inform you that the IRISMAN_4.87.pkg was compiled with the old german Language.ini.
datas\language_ini_gm.bin was not updated.

Thank you

**Comment by aldostools** [comment]
Thank you for let me know. I updated the INI but forgot to update the datas folder.

It should be fine now. You can download the updated package again.

Thanks again.

**Comment by ozapft** [comment]
Thanks Aldo,

I´ve downloaded and tested the package. But the language isn´t updated.

**Comment by aldostools** [comment]
I don't know what happened. Anyway I recompiled it again and this time I verified that the SELF on the PS3 has the changes.

My apologies for the inconveniences.

**Comment by ozapft** [comment]
You don´t have to apologize. 
Now it´s fixed.
Thank you very much for your work!
