### ISSUE TITLE
Version 4.87.1 Mounting PS3 ISO not possible

### ISSUE THREAD

**Issue by ozapft** [aldostools/IRISMAN#30]
Hello Aldo,

with the new version 4.87.1 it´s not possible to mount PS3 ISO´s.
After pressing X Button IRISMAN swithes to XMB without showing the Disk Icon.
I´ve tested this on HEN 4.86 with internal HDD and external NTFS Drives.

Best regards

**Comment by aldostools** [comment]
Thank you for your feedback.

I have uploaded a new build to releases with a fix for this issue. Please re-download and install the PKG
https://github.com/aldostools/IRISMAN/releases/tag/4.87.1

**Comment by ozapft** [comment]
It‘s working again.

Thank you!
