### ISSUE TITLE
[Bug] Makeps3iso doesn't use game name+id as ISO name when ripping with the BDVD controller option enabled.

### ISSUE THREAD

**Issue by ghost** [aldostools/IRISMAN#34]
Not sure whether it is possible or not on PS3. Makeps3iso 1.9 on PC has the option to use the "default name" for isos, which is the name + id of a rip found in the default param.sfo, I believe.

**Comment by aldostools** [comment]
IRISMAN already includes by default the game-id as part of the output name of the ISO

In this capture from IRISMAN, it shows that the default name for GT5 is "Gran Turismo 5-BCUS-98114.iso"
![image](https://user-images.githubusercontent.com/974897/117724010-26032480-b1b1-11eb-9125-88acdda004bb.png)

This is the code where the title id is appended to the file name:
https://github.com/aldostools/IRISMAN/blob/master/source/iso.c#L2475-L2479

**Comment by ghost** [comment]
Huh. I guess it only occurs when ripping directly to NTFS. If i remember correctly, the name set by makeps3iso is dev_bdvd.iso, or something along those lines. Perhaps this is a bug?

**Comment by aldostools** [comment]
As you can see in the following screen capture of IRISMAN, the output file name of Makeps3iso also includes the title id when the output folder is NTFS. In this case I selected to Build ISO of AC Brotherhood on /ntfs0:
![image](https://user-images.githubusercontent.com/974897/117725655-6fed0a00-b1b3-11eb-80f4-63b44158d230.png)

**Comment by ghost** [comment]
Well, this is what I'm getting from MAKEPS3ISo on my end (Sorry, not a screenshot). I'm using latest IRISMAN, with Rebug 4.86.1.
![IMG_20210510_142157189](https://user-images.githubusercontent.com/83893307/117726325-46c07f80-b19b-11eb-996b-8676531c8fa8.jpg)

**Comment by ghost** [comment]
Sorry, maybe I didn't specify this before, but I'm ripping the game directly from the Blu-Ray.

**Comment by aldostools** [comment]
Ok, it happens only when ripping directly from BDVD using the payload "With BDVD controller".

I will check what I can do to fix this issue.

**Comment by ghost** [comment]
Thanks. I'll change the title of the issue then.

**Comment by aldostools** [comment]
The issue should be fixed in the latest build. You can download the binary from the release page
https://github.com/aldostools/IRISMAN/releases

**Comment by ghost** [comment]
Wow, that was quick. Thanks for working on this.
