### ISSUE TITLE
Problem with launching new IRISMAN_4.86 on Rebug 4.85.1 LITE.

### ISSUE THREAD

**Issue by J013k** [aldostools/IRISMAN#5]
Hi.
I'm having problems with launching new IRISMAN_4.86.
After installation and setting the screen, message appear to install IRISMAN on /dev_hdd0/GAMES:
![https://i.postimg.cc/BntC81cC/iris.png](https://i.postimg.cc/BntC81cC/iris.png)
After that console freezes.

Currently I'm on Rebug 4.85.1 LITE CEX with Cobra 8.2 - CECH-2004A.

**Comment by aldostools** [comment]
Hello Jolek,
I'm on Rebug 4.84.2 REX and I've tried to reproduce your error doing a clean installation with Cobra enabled, but I didn't get the freeze.

I suggest you do the following:
1- Re-download the PKG from github, just in case you downloaded the test build
2- Delete the current IRISMAN from your system and install the version downloaded in step 1
3- Disconnect all USB devices (including controllers)
 
If you still get the issue, you could try downgrading to Rebug 4.84.2, although I think there shouldn't be any difference with 4.85 LITE or later.

**Comment by J013k** [comment]
Thanks for suggestions.
I downloaded IRISMAN from here:
[https://store.brewology.com/ahomebrew.php?brewid=250](https://store.brewology.com/ahomebrew.php?brewid=250).

I remember that after first fail, I've checked file system and rebuild database.
Deleted version 4.86.
Unfortunately second time I was getting the same issue.

I'll try to change language from Polish to English for test.
Re-download it again as you suggested.
Disconnect all USB devices.

Additionally I'll try to install previous version 4.85, to see if it is not a hardware problem.
Due the lack of time I'll try to do it in Friday.

Thanks for support & best regard.

**Comment by J013k** [comment]
I re-downloaded pkg (IRISMAN_4.86.pkg) from here...
md5sum of that file is 8958653df316d154772e42c97de338f0.

Additionally I'm only adjusting screen setting:
![https://i.postimg.cc/6pggnQRD/Add-irs2.png](https://i.postimg.cc/6pggnQRD/Add-irs2.png)

While installing IRISMAN 4.86 I've disconnected all USB devices.

Even when I'll change system language (EN-US) I'm still having this problem:
![https://i.postimg.cc/85BRpyNZ/Add-ris1.png](https://i.postimg.cc/85BRpyNZ/Add-ris1.png)

I do not have any problems with installing previous version 4.85 (IRISMAN_4.85.pkg.699.v4.85.pkg).

**Comment by J013k** [comment]
I've tried to install IRISMAN 4.86.1, but the problem still exists.

After updating FW from Rebug 4.8**5**.1 LITE to Rebug 4.8**6**.1 LITE,
I can finally launch IRISMAN 4.86.1.

So I don't know if it is some kind of a firmware problem...
Previous version of a IRISMAN 4.85 seems to be working fine on Rebug 4.85.1 LITE...

@aldostools what about for now add tag invalid?
Or you want to close this issue, because updating FW seems to help?

**Comment by aldostools** [comment]
I think the issue could be related to the auto start of webMAN MOD when IRISMAN is launched. It may not detecting if webMAN is running.

If the problem persists in the future, I suggest to edit the settings.ini to disable the auto start of webMAN.
