### ISSUE TITLE
Translation Question: What happened here?

### ISSUE THREAD

**Issue by HackZy01** [aldostools/IRISMAN#58]
Lines 177 and 178 in english langauge.ini have a conflicting meaning which makes translating it a bit more confusing

GLUTIL_HOLDTRIANGLEAB   = Hold CIRCLE to Abort
GLUTIL_HOLDTRIANGLESK   = Hold CIRCLE to Skip

By the name of the function you expect triangle, but by the text circle? I want to update my polish translation and wanted to ask

**Comment by HackZy01** [comment]
This too
225. DRAWPSX_PRESSOB         = Press TRIANGLE to change the order

**Comment by aldostools** [comment]
IRISMAN is based on the original code of Iris Manager.

The buttons used by Iris Manager were changes to a more standard layout like multiMAN.
The labels were adjusted but the internal variables never were renamed. That was in 2013 when I started to work on IRISMAN.

**Comment by HackZy01** [comment]
I'll adjust the translation to the new standard, btw. in polish they were still the old ones

**Comment by HackZy01** [comment]
I will create a pull request when i feel it's perfect
