### ISSUE TITLE
PS2/PSX PNG covers issue

### ISSUE THREAD

**Issue by fwannmacher** [aldostools/IRISMAN#61]
I think that there is a mistake in the way PS2/PSX covers are handles because in the code below it handles both JPG and PNG

https://github.com/aldostools/IRISMAN/blob/24bbce321cb160b0098fc0715402ecfe8ef235d7/source/psx.c#L620-L624

But in the code where the cover is searched it only looks for JPGs

https://github.com/aldostools/IRISMAN/blob/24bbce321cb160b0098fc0715402ecfe8ef235d7/source/main_icons.h#L456-L462

**Comment by aldostools** [comment]
The covers are searched as png or jpg if the images is in the same directory of the ISO.

It is only searched as JPG when it looks in multiMAN's covers database, that only has covers in JPG. The covers packages install JPG images too.

**Comment by fwannmacher** [comment]
Got it.

Not directly related but cover related I'm having a weird issue. I have my covers in mM folder but only few of them are loaded. There are 439 PS2 games and the covers are 260x300 JPGs. They all have the same name format but like I said just a few of them are loaded .

**Comment by aldostools** [comment]
The covers are loaded if the title id is detected and the image is found in the multiMAN's covers database.

Try copying the cover in the same directory of the game with the same name of the ISO but with the file extension jpg or png

**Comment by fwannmacher** [comment]
Worked like a charm ;)
