### ISSUE TITLE
Quality of life suggestions 

### ISSUE THREAD

**Issue by ghost** [aldostools/IRISMAN#67]
1: use circle to go back in file manager. This will greatly improve the user experience when navigating. Circle currently is just doing the same thing as triangle.

2: some kind of menu/pop up displaying all available buttons shortcuts. Example: start to view file manager help, select to view hex editor help, down to change sorting order of games, etc.

3: “< >” displayed next to some options in the file manager. I’ve been using IRISMAN for a number of years now, and only recently discovered that some of the options can be scrolled left/right — I can’t be alone.

4: exFAT manager font change. I’m not sure what is is about the current font, but it’s pretty hard to read.

**Comment by aldostools** [comment]
1. You can go back to the parent folder pressing SELECT+TRIANGLE. If you use it over .. it goes to root folder.
2. If you press START there is a help popup window that shows the shortcuts. In the hex editor the help button is SELECT due START is used to show the menu.
3. The left/right menu options are "easter eggs" to add more fun to the UX 😄 To be honest I was lazy to add these labels.
4. exFAT Manager was implemented with larger fonts recently.

**Comment by ghost** [comment]
> * You can go back to the parent folder pressing SELECT+TRIANGLE. If you use it over .. it goes to root folder.
> * If you press START there is a help popup window that shows the shortcuts. In the hex editor the help button is SELECT due START is used to show the menu.
> * The left/right menu options are "easter eggs" to add more fun to the UX 😄 To be honest I was lazy to add these labels.
> * exFAT Manager was implemented with larger fonts recently.

I did not know about number 1 as it’s not mentioned in the help (start) text. After testing now, I have a couple of points to make: 1. Pressing select + start on ‘..’ goes to the root folder instead of previous. 2. Pressing select + start in general doesn’t remember the previous cursor positions, unlike using the ‘..’ option. I’m sure both of these are probably intentional, but it’s worth mentioning just in case.

2: I discovered this a while ago by accident. I actually meant some kind of indicator telling the user to press select/start to see the controls. Still, not a big deal.

3: That’s understandable :P

4: I noticed that. Thank you for the change :)
