### ISSUE TITLE
Irisman 4.86.1 doesn't support fw 4.85

### ISSUE THREAD

**Issue by plt2so6bis** [aldostools/IRISMAN#7]
It's freeze just after creating the game folder, the folder was really created but freeze and after reboot just black screen

**Comment by J013k** [comment]
Update your FW:
[https://github.com/aldostools/IRISMAN/issues/5#issuecomment-616022915](https://github.com/aldostools/IRISMAN/issues/5#issuecomment-616022915).

**Comment by plt2so6bis** [comment]
Yes but for now I'm just installed the irisman4.85 and work fine. I'll upgrade all later thanks for help and thanks for your work all the developer
