### ISSUE TITLE
Unexpected behaviour with exFAT Manager changes

### ISSUE THREAD

**Issue by ghost** [aldostools/IRISMAN#70]
First of all, “/..” isn’t listed if you go directly to a usb device (not through sys, but through fat for example). Then there’s the weird behaviour when backing out of folders. Both circle and /.. can be used. However, if /.. is used and then circle is pressed, it will actually take you back into the folder you were just in instead of continuing to go back. I understand this might be somewhat difficult to understand, so here’s an example for you to try:

1: navigate to /dev_hdd0/game/IRISMAN00.
2: press /… to return to /dev_hdd0/game.
3: press circle. You will now be back in /dev_hdd0/game/IRISMAN00.

**Comment by Masamune3210** [comment]
afaik circle acts like back in a file browser, rather than up. So going to the folder, using the ../ to go up, and then hitting circle would be going back in the history, in this case going back to the directory before you used the ../

**Comment by ghost** [comment]
I also just wanted to add that holding L2 can still be used to select files while scrolling, but not single files anymore. Would it be possible to restore this, or allow holding square to select files while scrolling instead?

A solution for the original issue would be to have the /.. option call the same function as pressing circle. It’s not a huge problem, but navigating back to dev_hdd0 with /.. only to have to press circle several more times to close the manager is a bit of an annoyance.

**Comment by aldostools** [comment]
In the latest build uploaded today I re-added L2 for single selection and added SQUARE for scroll selection.
Also changed /.. to behave like pressing CIRCLE

**Comment by ghost** [comment]
Thank you, aldo :)
