### ISSUE TITLE
exFAT Manager suggestion

### ISSUE THREAD

**Issue by ghost** [aldostools/IRISMAN#72]
I don’t know how complicated this would be to implement, but it’s already in IRISMAN’s native file manager - my suggestion is to have folders sorted before files.

**Comment by aldostools** [comment]
The exFAT Manager was already grouping folders before files.
I've made a small change to improve this feature (possible bug fix)

**Comment by ghost** [comment]
It seems to have the same behaviour as the native file manager now. Nice work, and thanks.
