### ISSUE TITLE
Need help getting everything required to compile

### ISSUE THREAD

**Issue by ghost** [aldostools/IRISMAN#88]
At the moment, I can’t test anything until you’ve merged the pull requests and uploaded a new pkg. This means I’ve only been fixing the simple things.

Would you be able to tell me everything I need to compile for myself, please. I’d like to keep working on IRISMAN, but the way things are at the moment aren’t ideal.

**Comment by aldostools** [comment]
This is the PSL1GHT SDK needed to compile the project.
https://github.com/Estwald/PSDK3v2

Follow the instructions. They are in Spanish. 

You may to edit the batch files included in the project to use the paths in your environment.

 I use _Make_EBOOT.BIN.bat to create RELOAD.SELF then I replace it in the PKG that I distribute. Maybe you could use Make_PKG.bat but I don't remember if it still works.

**Comment by ghost** [comment]
> This is the PSL1GHT SDK needed to compile the project. https://github.com/Estwald/PSDK3v2
> 
> Follow the instructions. They are in Spanish.
> 
> You may to edit the batch files included in the project to use the paths in your environment.
> 
> I use _Make_EBOOT.BIN.bat to create RELOAD.SELF then I replace it in the PKG that I distribute. Maybe you could use Make_PKG.bat but I don't remember if it still works.

Thank you. I installed the SDK, but I am getting "fatal error: unrar.h: No such file or directory
compilation terminated." when I try to compile it.

**Comment by aldostools** [comment]
Ah that's an update from bucanero. Let me find the file.

**Comment by aldostools** [comment]
Extract [include.zip](https://github.com/aldostools/IRISMAN/files/10756424/include.zip) and put the files in `C:\PSDK3v2\ps3dev\portlibs\ppu\include`  (or the corresponding path in your system)

**Comment by aldostools** [comment]
Extract [lib.zip](https://github.com/aldostools/IRISMAN/files/10756454/lib.zip) and put the files in `C:\PSDK3v2\ps3dev\portlibs\ppu\lib` (or the corresponding path in your system)

**Comment by ghost** [comment]
@aldostools this is gonna sound really stupid, but I need some advice on where to declare a bool. I'm trying to fix some stuff in the exfat manager, and need to use this specific bool in fsutil.c and fmapp.c. So far, I either get an error about it being declared multiple times (despite it not), or that it is undeclared. It's driving me crazy

**Comment by aldostools** [comment]
Try using a different name or use

#ifndef MYVAR
#define MYVAR
static bool myvar = false;
#endif

**Comment by ghost** [comment]
Thank you. That worked :)
